name: geo
channels:
    - conda-forge
dependencies:
    - nodejs
    - ipyleaflet
    - jupyterlab=3
    - datapane
    - folium
    - imageio
    - keplergl
    - leafmap
    - pydeck
    - xarray_leaflet
    - geopandas
    - osmnx
    - tifffile
    - geemap
