name: docs
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m pip install --upgrade pip
      - run: pip install mkdocs mkdocs-material mkdocstrings mkdocs-git-revision-date-plugin mkdocs-jupyter ipykernel livereload leafmap geemap
      - run: mkdocs gh-deploy --force
        env:
          USE_MKDOCS: ${{ secrets.USE_MKDOCS }}
