name: docs
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir Cython
                  pip install codespell -r requirements.txt
                  pip install .
            - name: Discover typos with codespell
              run: codespell --skip="*.csv,*.geojson,*.json,*.js,*.html,*cff" --ignore-words-list="aci,acount,acounts,fallow,hart,hist,nd,ned,ois,wqs,mesage"
            - name: PKG-TEST
              run: |
                  pip install xarray_leaflet geopandas osmnx sqlalchemy psycopg2 keplergl datapane
                  python -m unittest discover tests/
              env:
                  PLANET_API_KEY: ${{ secrets.PLANET_API_KEY }}
            - run: python -m pip install --upgrade pip
            - run: pip install mkdocs mkdocs-material mkdocstrings mkdocs-git-revision-date-plugin mkdocs-jupyter ipykernel livereload
            - run: mkdocs gh-deploy --force
              env:
                  USE_FOLIUM: ${{ secrets.USE_FOLIUM }}
                  USE_MKDOCS: ${{ secrets.USE_MKDOCS }}
                  HEREMAPS_API_KEY: ${{ secrets.HEREMAPS_API_KEY }}
                  DP_TOKEN: ${{ secrets.DP_TOKEN }}
